capstone/pennywiser/pennywise/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register, name="register"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("new_transaction", views.new_transaction, name="new_transaction"),
    path("settings", views.settings, name="settings"),
    path("archive", views.archive, name="archive"),
    path("edit", views.edit, name="edit"),
    path("accounts", views.accounts, name="accounts"),
    path("account_statement", views.accounts, name="account_statement"),
    path("overview", views.overview, name="overview"),
    path("swap_company", views.swap_company, name="swap_company")
]

capstone/pennywiser/pennywise_hub/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pennywise.urls"))
]

capstone/pennywiser/pennywise/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime
from dateutil.relativedelta import relativedelta

class User(AbstractUser):
    pass

class Company(models.Model):
    name = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owned_companies") # Creator of the company's account

    class Meta:
        verbose_name_plural = "Companies"
        constraints = [
            models.UniqueConstraint(fields=["name", "user"], name="user_company")
        ]

    def __str__(self):
        return self.name
    
class CompanyUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="companies")
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="company_users")
    access_level = models.IntegerField(default=1)

    def __str__(self):
         return f"{self.company} - {self.user}"
    
class Category(models.Model):
    TYPE_CHOICES = {
        "E": "Expense",
        "I": "Income"
    }

    name = models.CharField(max_length=30)
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="categories")

    class Meta:
        verbose_name_plural = "Categories"
        constraints = [
            models.UniqueConstraint(fields=["name", "company"], name="company_category")
        ]
    
    def __str__(self):
        return f"{self.company} - {self.type} - {self.name}"

class Account(models.Model):
    name = models.CharField(max_length=30)
    balance = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="accounts")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["name", "company"], name="company_account")
        ]

    def __str__(self):
        return f"{self.company} - {self.name}"
    
    
class MonthlyAccountBalance(models.Model):
    balance = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    month_year = models.DateField() # Saving the first day of the month, example: April 2024 will be saved as 2024-04-01)
    account = models.ForeignKey(Account, on_delete=models.PROTECT, related_name="monthly_balances")

    def __str__(self):
        return f"{self.account} - {self.month_year.month}/{self.month_year.year} - {self.balance}"


class Transaction(models.Model):
    REPLICATE_CHOICES = {
        "O": "Once",
        "M": "Monthly",
        "B": "Bimonthly",
        "Q": "Quarterly",
        "Y": "Yearly"
    }

    due_date = models.DateField()
    description = models.CharField(max_length=255)
    payment_info = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    installments = models.IntegerField(null=True, blank=True)
    current_installment = models.IntegerField(null=True, blank=True)
    replicate = models.CharField(max_length=1, choices=REPLICATE_CHOICES, default="O") # Expenses with more than one installment can only have this set to "once" or "yearly" (if more than 12 installments, only to "once")
    has_replicated = models.BooleanField(default=False)
    parent_id = models.IntegerField(null=True, blank=True) # If replicated, stores parent's transaction id for replicating purposes
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="category_transactions")
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="company_transactions")
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="user_transactions")
    settle_account = models.ForeignKey(Account, null=True, blank=True, on_delete=models.PROTECT, related_name="account_transactions")
    settle_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="settle_user_transactions")
    settle_date = models.DateField(null=True, blank=True)
    settle_description = models.CharField(null=True, blank=True, max_length=255)
    settle_receipt = models.ImageField(null=True, blank=True, upload_to="pennywise/files/receipts")
    payment_slip = models.ImageField(null=True, blank=True, upload_to="pennywise/files/payment_slips")
    
    def has_expired(self):
        today = datetime.today().date()
        return self.due_date < today
    
    def is_last_day_of_month(self):
        date = self.due_date.replace(day=1) + relativedelta(months=1) - relativedelta(days=1)
        return date == self.due_date
    
    def is_weekend(self):
        return self.due_date.weekday() > 4
    
    def __str__(self):
        return f"{self.company} - {self.id}"
    
class Timer(models.Model):
    db_date = models.DateField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="timer")

    def __str__(self):
        return f"{self.db_date}"

capstone/pennywiser/pennywise/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from django.core.paginator import Paginator
from django.db.models import Sum, Q

from .models import User, Company, CompanyUser, Category, Account, Transaction, MonthlyAccountBalance, Timer


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        company_name = request.POST["company"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "pennywise/register.html", {
                "error": "Passwords must match."
            })

        '''
        # Check if company name is taken
        if Company.objects.filter(name=company_name).exists():
            return render(request, "pennywise/register.html", {
                "error": "Company name already taken."
            })
        '''

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "pennywise/register.html", {
                "error": "Username unavailable."
            })
        
        # Create company
        company = Company(name=company_name, user=user)
        company.save()

        # Create company-user relation
        company_user = CompanyUser(user=user, company=company, access_level=1)
        company_user.save()

        # Create basic transfer categories to be used in any company
        transfer_out_category = Category(name="Transfer Out", type="E", company=company)
        transfer_in_category = Category(name="Transfer In", type="I", company=company)
        transfer_out_category.save()
        transfer_in_category.save()
        
        # Create a database date stores for replicating purposes
        timer = Timer(db_date=datetime.today().date(), company=company)
        timer.save()

        login(request, user)
        companies = []
        for company in user.owned_companies.all():
            companies.append(company.name)
        request.session["company"] = user.owned_companies.all()[0].name
        request.session["company_id"] = user.owned_companies.all()[0].id
        request.session["companies"] = companies

        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "pennywise/register.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        # Check if authentication successful
        if user is not None:
            login(request, user)
            list_of_owned_companies = []
            owned_companies = user.owned_companies.all()
            for company in owned_companies:
                list_of_owned_companies.append(company.name)
            request.session["company"] = owned_companies[0].name
            request.session["company_id"] = owned_companies[0].id
            request.session["companies"] = list_of_owned_companies
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "pennywise/login.html", {
                "error": "Invalid username and/or password."
            })
    else:
        return render(request, "pennywise/login.html")
    

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


@login_required
def index(request):
    timer = Timer.objects.get(company=request.session["company_id"])
    today = datetime.today().date()

    if (timer.db_date != today):
        timer.db_date = today
        timer.save()
        expired_transactions = Transaction.objects.filter(
            ~Q(replicate="O"), company=request.session["company_id"], due_date__lt=today, has_replicated=False).exclude(current_installment__gt=1)
        for transaction in expired_transactions:
            if transaction.replicate == "M":
                months = 1
            elif transaction.replicate == "B":
                months = 2
            elif transaction.replicate == "Q":
                months = 3
            elif transaction. replicate == "Y":
                months = 12
            
            while transaction.due_date < today:
                due_date = transaction.due_date + relativedelta(months=months)
                new_transaction = Transaction(company=transaction.company, user=transaction.user, due_date=due_date, category=transaction.category, amount=transaction.amount, payment_info=transaction.payment_info,
                                              description=transaction.description, replicate=transaction.replicate, installments=transaction.installments, current_installment=transaction.current_installment, parent_id=transaction.id)
                new_transaction.save()
                # Check if new transaction due_date should be last day of month, comparing with parent's transaction
                if transaction.is_last_day_of_month() and not new_transaction.is_last_day_of_month():
                    try:
                        parent_transaction = Transaction.objects.get(id=transaction.parent_id)
                    except:
                        parent_transaction = None
                    if parent_transaction:
                        if parent_transaction.is_last_day_of_month():
                            new_transaction.due_date = new_transaction.due_date.replace(day=1) + relativedelta(months=1) - relativedelta(days=1)
                            new_transaction.save()
                    else:
                        new_transaction.due_date = new_transaction.due_date.replace(day=1) + relativedelta(months=1) - relativedelta(days=1)
                        new_transaction.save()

                if transaction.replicate == "Y" and transaction.installments:
                    for i in range(2, int(transaction.installments)+1):
                        new_transaction_installments = Transaction(company=transaction.company, user=transaction.user, due_date=new_transaction.due_date + relativedelta(months=i-1), category=transaction.category,
                                                                   amount=transaction.amount, payment_info=transaction.payment_info, description=transaction.description, replicate=transaction.replicate, installments=transaction.installments, current_installment=i)
                        new_transaction_installments.save()
                    
                transaction.has_replicated = True
                transaction.save()
                transaction = new_transaction

    message = None
    error = None
    # By default the page loads on the expenses tab, this variable changes to the income tab if a form was sent from income
    came_from_income = False 
    if request.method == "POST":
        settle_description = request.POST["settle_description"]
        amount = request.POST["amount"]
        settle_date = request.POST["settle_date"]
        transaction_id = request.POST["transaction_id"]
        transaction = Transaction.objects.get(id=transaction_id)
        try:
            account = Account.objects.get(id=request.POST["account_id"])
        except:
            account = None
            error = "Must select an account."
            if transaction.category.type == "I":
                came_from_income = True

        if account:
            # Update transaction with settle information
            transaction.settle_description = settle_description
            transaction.amount = amount
            transaction.settle_date = settle_date
            transaction.settle_user = request.user
            transaction.settle_account = account
            transaction.save()

            date = datetime.strptime(settle_date, "%Y-%m-%d").replace(day=1).date()
            # Try to get an instance of the account's monthly balance, creates one if it doesn't exist
            try:
                monthly_balance = MonthlyAccountBalance.objects.get(account=account, month_year=date)
            except:
                monthly_balance = MonthlyAccountBalance(account=account, month_year=date)

            # Update account balance
            if transaction.category.type == "E":
                account.balance = float(account.balance) - float(amount)
                monthly_balance.balance = float(monthly_balance.balance) - float(amount)
            else:
                account.balance = float(account.balance) + float(amount)
                monthly_balance.balance = float(monthly_balance.balance) + float(amount)
                came_from_income = True

            account.save()
            monthly_balance.save()
            message = "Transaction settled successfully."

    accounts = Account.objects.filter(company=request.session["company_id"])
    upcoming = today + timedelta(10)
    todays_expenses = Transaction.objects.filter(category__type="E", due_date__lte=today, company=request.session["company_id"], settle_date__isnull=True).order_by("due_date")
    todays_expenses_total = todays_expenses.aggregate(Sum("amount"))["amount__sum"]
    upcoming_expenses = Transaction.objects.filter(category__type="E", due_date__range=(today+timedelta(1), upcoming), company=request.session["company_id"], settle_date__isnull=True).order_by("due_date")
    upcoming_expenses_total = upcoming_expenses.aggregate(Sum("amount"))["amount__sum"]

capstone/pennywiser/pennywise/templates/pennywise/account_statement.html
{% extends "pennywise/layout.html" %}

{% block body %}

<div class="container">
    <h2>{{ date }} Statement</h2>
    <table class="table table-hover">
        <thead class="table-light">
            <tr>
                <th scope="col" colspan="4">{{ account.name }}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {% if carry_over >= 0 %}
                    <td scope="col" colspan="4" style="text-align:right">Carry-over: <span class="text-success">{{ carry_over|floatformat:2 }}</span></td>
                {% else %}
                    <td scope="col" colspan="4" style="text-align:right">Carry-over: <span class="text-danger">{{ carry_over|floatformat:2 }}</span></td>
                {% endif %}
            </tr>
            {% for transaction in transactions %}
                <tr>
                    <td>{{ transaction.settle_date }}</td>
                    {% if transaction.category.type == "I" %}
                        <td style="text-align:left">{{ transaction.description }}</td>
                        {% if transaction.installments %}
                            <td>{{ transaction.current_installment }}/{{ transaction.installments }}</td>
                        {% else %}
                            <td></td>
                        {% endif %}
                        <td class="text-success">{{ transaction.amount }}</td>
                    {% else %}
                        <td style="text-align:right">{{ transaction.description }}</td>
                        {% if transaction.installments %}
                            <td>{{ transaction.current_installment }}/{{ transaction.installments }}</td>
                        {% else %}
                            <td></td>
                        {% endif %}
                        <td class="text-danger">{{ transaction.amount }}</td>
                    {% endif %}
                </tr>
            {% endfor %}
            <tr>
                <td colspan="4" style="text-align:right"><strong>Balance: </strong>{{ balance|floatformat:2 }}</td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock %}

capstone/pennywiser/pennywise/templates/pennywise/edit.html
{% extends "pennywise/layout.html" %}

{% block body %}

    <div class="forms">
        <h2>Edit Transaction</h2>

        {% if message %}
            <div id="message" class="alert alert-success">{{ message }}</div>
        {% elif error %}
            <div id="message" class="alert alert-danger">{{ error }}</div>
        {% endif %}
        
        <form action="{% url 'edit' %}" id="edit_form" method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input class="form-control" autocomplete="off" id="due_date" name="due_date" type="date" value="{{ transaction.due_date|date:"Y-m-d" }}" required>
                <label for="due_date">Due date</label>
            </div>
            <div class="form-floating mb-3">
                {% if transaction.settle_date %}
                    <input class="form-control" autocomplete="off" id="settle_date" name="settle_date" type="date" value="{{ transaction.settle_date|date:"Y-m-d" }}" required>
                {% else %}
                    <input class="form-control" autocomplete="off" id="settle_date" name="settle_date" type="date" disabled>
                {% endif %}
                <label for="settle_date">Settle date</label>
            </div>
            <div class="form-floating mb-3">
                {% if transaction.settle_date %}
                    <select class="form-control" name="account" id="account" required>
                        {% for account in accounts %}
                            {% if account.id == transaction.settle_account.id %}
                                <option value="{{ account.id }}" selected>{{ account.name }}</option>
                            {% else %}
                                <option value="{{ account.id }}">{{ account.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                {% else %}
                    <select class="form-control" name="account" id="account" disabled></select>
                {% endif %}
                <label for="account">Account</label>
            </div>
            <div class="form-floating mb-3">
                <select class="form-control" name="category" id="category" required>
                    <option value="none" disabled>-- {{ transaction.category.get_type_display }} categories --</option>
                    {% for category in categories %}
                        {% if category.id == transaction.category.id %}
                            <option value="{{ category.id }}" selected>{{ category.name }}</option>
                        {% else %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
                <label for="category">Category</label>
            </div>
            <div class="form-floating mb-3">
                <input class="form-control" autocomplete="off" id="amount" name="amount" type="number" min="0" step="0.01" value="{{ transaction.amount }}">
                <label for="amount">Amount</label>
            </div>
            <div class="form-floating mb-3">
                <textarea class="form-control" maxlength="255" autocomplete="off" id="payment_info" name="payment_info">{{ transaction.payment_info }}</textarea>
                <label for="payment_info">Payment Info</label>
            </div>
            <div class="form-floating mb-3">
                <textarea class="form-control" maxlength="255" autocomplete="off" id="description" name="description" required>{{ transaction.description }}</textarea>
                <label for="description">Description</label>
            </div>
            <div class="form-floating mb-3">
                {% if transaction.settle_date %}
                    <textarea class="form-control" maxlength="255" autocomplete="off" id="settle_description" name="settle_description">{{ transaction.settle_description }}</textarea>
                {% else %}
                    <textarea class="form-control" maxlength="255" autocomplete="off" id="settle_description" name="settle_description" disabled></textarea>
                {% endif %}
                <label for="settle_description">Settle description</label>
            </div>
            <div class="check-form">
                <p>Replicate: <strong>{{ transaction.get_replicate_display }}</strong></p>
            </div>
            {% if transaction.installments %}
                <div class="check-form">
                    <p>Installment: <strong>{{ transaction.current_installment }} / {{ transaction.installments }}</strong></p>
                </div>
                {% if not transaction.settle_date %}
                    <div class="check-form">
                        <label class="form-check-label" for="apply_to_next_installments">Apply to next installments&nbsp;</label>
                        <input class="form-check-input" type="checkbox" value=True name="apply_to_next_installments" id="apply_to_next_installments">
                        &nbsp;<abbr title="Amount, description and deletition only">⍰</abbr>
                    </div>
                    <br>
                {% endif %}
            {% endif %}
            <input type="hidden" name="transaction_id" value="{{ transaction.id }}">
            <button class="btn btn-primary" name="edit" value="edit_transaction" type="submit">Save</button>
            <button class="btn btn-secondary position-absolute start-50 translate-middle-x" name="edit" value="copy_transaction" type="submit">Copy</button>
            <button class="btn btn-warning" id="confirmation" name="edit" value="delete_transaction" type="submit" style="display:none" ;>Delete?</button>
        </form>
        <button class="btn btn-danger" id="delete" onclick="showDeleteConfirmation()">Delete</button>
    </div>

{% endblock %}

capstone/pennywiser/pennywise/templates/pennywise/new_transaction.html
{% extends "pennywise/layout.html" %}

{% block body %}

    <div class="forms">
        <h2>New Transaction</h2>

        {% if message %}
            <div id="message" class="alert alert-success">{{ message }}</div>
        {% elif error %}
            <div id="message" class="alert alert-danger">{{ error }}</div>
        {% endif %}
        
        <form action="{% url 'new_transaction' %}" id="transaction_form" method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input class="form-control" autocomplete="off" id="due_date" name="due_date" type="date" value="{{ today|date:"Y-m-d" }}">
                <label for="due_date">Due date</label>
            </div>
            {% if transaction %}
                <div class="form-floating mb-3">
                    <select class="form-control" name="category" id="category" required>
                        <option value="none" disabled>-- {{ transaction.category.get_type_display }} categories --</option>
                        {% for category in categories %}
                            {% if category.id == transaction.category.id %}
                                <option value="{{ category.id }}" selected>{{ category.name }}</option>
                            {% else %}
                                <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                    <label for="category">Category</label>
                </div>
                <div class="form-floating mb-3">
                    <input class="form-control" autocomplete="off" id="amount" name="amount" type="number" min="0" step="0.01" value="{{ transaction.amount }}">
                    <label for="amount">Amount</label>
                </div>
                <div class="form-floating mb-3">
                    <textarea class="form-control" maxlength="255" autocomplete="off" id="payment_info" name="payment_info">{{ transaction.payment_info }}</textarea>
                    <label for="payment_info">Payment Info</label>
                </div>
                <div class="form-floating mb-3">
                    <textarea class="form-control" maxlength="255" autocomplete="off" id="description" name="description" required>{{ transaction.description }}</textarea>
                    <label for="description">Description</label>
                </div>
            {% else %}
                <div class="form-floating mb-3">
                    <select class="form-control" name="category" id="category" required>
                        <option value="none" selected disabled>Choose category</option>
                        <option value="none" disabled>-- Expense --</option>
                        {% for category in expense_categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        {% empty %}
                            <option value="none" disabled>No expense categories yet.</option>
                        {% endfor %}
                        <option value="none" disabled>-- Income --</option>
                        {% for category in income_categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        {% empty %}
                            <option value="none" disabled>No income categories yet.</option>
                        {% endfor %}
                    </select>
                    <label for="category">Category</label>
                </div>
                <div class="form-floating mb-3">
                    <input class="form-control" autocomplete="off" id="amount" name="amount" type="number" min="0" step="0.01" required>
                    <label for="amount">Amount</label>
                </div>
                <div class="form-floating mb-3">
                    <textarea class="form-control" maxlength="255" autocomplete="off" id="payment_info" name="payment_info"></textarea>
                    <label for="payment_info">Payment Info</label>
                </div>
                <div class="form-floating mb-3">
                    <textarea class="form-control" maxlength="255" autocomplete="off" id="description" name="description" required></textarea>
                    <label for="description">Description</label>
                </div>
            {% endif %}
            <div class="check-form">
                <p class="form-check-inline">Replicate:</p>
                <div class="form-check-inline">
                    <input class="form-check-input" type="radio" id="once" name="replicate" value="O" checked="checked" onchange="enableInstallment()">
                    <label class="form-check-label" for="replicate">Once</label>
                </div>
                <div class="form-check-inline">
                    <input class="form-check-input" type="radio" id="monthly" name="replicate" value="M" onchange="disableInstallment()">
                    <label class="form-check-label" for="replicate">Monthly</label>
                </div>
                <div class="form-check-inline">
                    <input class="form-check-input" type="radio" id="bimonthly" name="replicate" value="B" onchange="disableInstallment()">
                    <label class="form-check-label" for="replicate">Bimonthly</label>
                </div>
                <div class="form-check-inline">
                    <input class="form-check-input" type="radio" id="quarterly" name="replicate" value="Q" onchange="disableInstallment()">
                    <label class="form-check-label" for="replicate">Quarterly</label>
                </div>
                <div class="form-check-inline mb-3">
                    <input class="form-check-input" type="radio" id="yearly" name="replicate" value="Y" onchange="enableInstallment()">
                    <label class="form-check-label" for="replicate">Yearly</label>
                </div>
            </div>
            <div class="check-form">
                <label class="form-check-label" for="has_installments">Has installments&nbsp;</label>
                <input class="form-check-input" type="checkbox" value=True name="has_installments" id="has_installments" onchange="showInstallments(this)">
            </div>
            <div class="form-group">
                <input class="form-control mx-auto" autocomplete="off" autofocus id="installments" name="installments" type="number" min="2" step="1" onchange="checkInstallments(this)">
            </div>
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>

{% endblock %}